import { Component, computed, effect, inject, signal, untracked } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { PageShellComponent } from './page-shell.component';
import { BrandComponent } from '../shared/brand/brand.component';
import { ProjectService } from '../services/project.service';
import { TaskService } from '../services/task.service';
import { ThemeService } from '../services/theme.service';
import { TaskModalComponent } from '../task-modal/task-modal.component';
import { Task } from '../models';
import { STORAGE_PROVIDER } from '../providers/storage.provider';

const imports=[CommonModule,RouterLink,PageShellComponent];

@Component({standalone:true,imports:[...imports,BrandComponent],template:`
<app-page-shell title="Moins de dispersion. Plus d’équilibre." description="Ma’at vous aide à transformer vos idées en actions, dans un espace clair et personnel.">
 <section class="grid items-center gap-8 rounded-2xl border border-blue-100 bg-blue-50 p-8 dark:border-blue-900 dark:bg-blue-950 sm:grid-cols-2">
  <div><app-brand /><h2 class="mt-4 text-2xl font-semibold">Une tâche après l’autre.</h2><p class="my-4 leading-7 text-gray-600 dark:text-gray-300">Inspirée de l’équilibre associé à Ma’at, l’application rassemble vos tâches, projets et échéances. Gardez une vue simple de ce qui compte.</p><div class="flex flex-wrap gap-4"><a class="primary min-h-11" routerLink="/board">Ouvrir mon tableau</a><a class="secondary min-h-11" routerLink="/login">Connexion / Inscription</a></div></div>
  <div class="grid gap-4" aria-label="Fonctionnement du tableau"><div *ngFor="let step of steps; let i=index" class="rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800"><p class="text-xs text-blue-700 dark:text-blue-300">0{{i+1}}</p><h3 class="mt-2 font-semibold">{{step.title}}</h3><p class="mt-2 text-sm text-gray-600 dark:text-gray-300">{{step.text}}</p></div></div>
 </section>
 <section class="mt-8 grid gap-4 sm:grid-cols-3"><article *ngFor="let benefit of benefits" class="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><h2 class="font-semibold">{{benefit.title}}</h2><p class="mt-2 text-sm leading-6 text-gray-600 dark:text-gray-300">{{benefit.text}}</p></article></section>
 <p class="mt-8 text-sm text-gray-600 dark:text-gray-300">Sans compte, vos données restent sur cet appareil. Connectez-vous pour utiliser la sauvegarde cloud. La collaboration d’équipe n’est pas encore disponible.</p>
</app-page-shell>`})
export class PresentationComponent {
 readonly steps=[{title:'À faire',text:'Capturez une idée et choisissez sa priorité.'},{title:'En cours',text:'Concentrez-vous sur votre prochaine action.'},{title:'Terminé',text:'Visualisez vos avancées et archivez si nécessaire.'}];
 readonly benefits=[{title:'Organisez vos projets',text:'Regroupez les tâches sans multiplier les outils.'},{title:'Anticipez les échéances',text:'Retrouvez les tâches datées dans votre calendrier.'},{title:'Gardez le contrôle',text:'Filtres, sous-tâches, sauvegardes et thème sombre : choisissez votre rythme.'}];
}

@Component({standalone:true,imports:[...imports,FormsModule],template:`
<app-page-shell title="Mes projets" description="Regroupez vos tâches par projet. Ces projets appartiennent à votre espace personnel ; ils ne sont pas des tableaux partagés.">
 <form (ngSubmit)="save()" class="mb-4 flex flex-wrap items-end gap-4 rounded-xl border border-gray-200 p-4 dark:border-gray-700"><label class="grid flex-1 gap-2 text-sm" for="project-title">{{editing ? 'Renommer le projet' : 'Nouveau projet'}}<input id="project-title" name="title" [(ngModel)]="draft" required maxlength="100" class="min-h-11 w-full rounded-lg border border-gray-300 bg-white p-2 dark:border-gray-600 dark:bg-gray-800" placeholder="Ex. Lancement de mon site"></label><button class="primary min-h-11" type="submit">{{editing ? 'Enregistrer' : 'Créer le projet'}}</button><button *ngIf="editing" type="button" class="secondary min-h-11" (click)="cancel()">Annuler</button></form>
 <p *ngIf="message() || projects.error()" role="status" class="mb-4 rounded-lg bg-blue-50 p-4 text-sm text-blue-800 dark:bg-blue-950 dark:text-blue-200">{{projects.error() || message()}}</p>
 <label class="mb-4 flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" [(ngModel)]="showArchived">Afficher les projets archivés</label>
 <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3" aria-label="Liste des projets"><article *ngFor="let project of visibleProjects()" class="min-w-0 rounded-xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800"><span *ngIf="project.archived" class="text-xs text-gray-600 dark:text-gray-300">Archivé</span><h2 class="break-words text-lg font-semibold">{{project.title}}</h2><p class="my-4 text-sm text-gray-600 dark:text-gray-300">{{count(project.id)}} tâches actives · {{count(project.id,true)}} terminées</p><div class="flex flex-wrap gap-2"><a class="primary min-h-11" routerLink="/board" [queryParams]="{project:project.id}">Ouvrir</a><button class="secondary min-h-11" (click)="editing=project.id; draft=project.title">Renommer</button><button class="secondary min-h-11" (click)="archive(project.id)">{{project.archived ? 'Restaurer' : 'Archiver'}}</button></div></article></section>
 <p *ngIf="!visibleProjects().length" class="rounded-xl border border-gray-200 p-8 text-center text-gray-600 dark:border-gray-700 dark:text-gray-300">Aucun projet à afficher. Créez votre premier projet ci-dessus.</p>
</app-page-shell>`})
export class ProjectsComponent {
 readonly projects=inject(ProjectService); readonly tasks=inject(TaskService);
 draft=''; editing:string|undefined; showArchived=false; readonly message=signal('');
 visibleProjects(){return this.projects.projects().filter(p=>this.showArchived||!p.archived);}
 count(id:string,done=false){return this.tasks.activeTasks().filter(t=>t.projectId===id&&(!done||t.status==='done')).length;}
 cancel(){this.draft='';this.editing=undefined;}
 save(){this.run(()=>{this.projects.save(this.draft,this.editing);this.cancel();this.message.set('Projet enregistré.');});}
 archive(id:string){this.run(()=>this.projects.archive(id));}
 private run(action:()=>void){this.message.set('');try{action();}catch(e){this.message.set(e instanceof Error?e.message:'Action impossible.');}}
}

export function localDayKey(date:Date):string {return date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');}
export function calendarDays(year:number,month:number):(Date|null)[] {
 const offset=(new Date(year,month,1).getDay()+6)%7;
 const days:(Date|null)[]=Array.from({length:offset},()=>null);
 for(let day=1;day<=new Date(year,month+1,0).getDate();day++)days.push(new Date(year,month,day));
 while(days.length%7)days.push(null);return days;
}
@Component({standalone:true,imports:[...imports,TaskModalComponent],template:`
<app-page-shell title="Calendrier" description="Vos échéances, au même endroit. Sélectionnez une tâche pour consulter ou modifier ses détails.">
 <div class="mb-4 flex flex-wrap items-center justify-between gap-4"><h2 class="text-xl font-semibold" aria-live="polite">{{monthLabel()}}</h2><div class="flex gap-2"><button class="secondary min-h-11" aria-label="Mois précédent" (click)="move(-1)">←</button><button class="secondary min-h-11" (click)="today()">Aujourd’hui</button><button class="secondary min-h-11" aria-label="Mois suivant" (click)="move(1)">→</button></div></div>
 <div class="hidden overflow-hidden rounded-xl border border-gray-200 dark:border-gray-700 md:block"><div class="grid grid-cols-7 bg-gray-50 text-center text-xs dark:bg-gray-800"><div *ngFor="let day of weekdays" class="p-4">{{day}}</div></div><div class="grid grid-cols-7"><div *ngFor="let day of days()" class="min-h-28 min-w-0 border-t border-gray-200 p-2 dark:border-gray-700" [class.bg-blue-50]="day && isToday(day)" [class.dark:bg-blue-950]="day && isToday(day)"><ng-container *ngIf="day"><p class="mb-2 text-xs font-semibold">{{day.getDate()}}</p><button *ngFor="let task of tasksFor(day)" class="mb-2 block min-h-11 w-full break-words rounded-lg bg-gray-100 p-2 text-left text-xs hover:bg-blue-100 dark:bg-gray-800 dark:hover:bg-blue-900" (click)="open(task)">{{task.title}}<span *ngIf="task.status==='done'"> ✓</span></button></ng-container></div></div></div>
 <section class="mt-8"><h2 class="mb-4 text-lg font-semibold">Échéances du mois · {{agenda().length}}</h2><div *ngFor="let task of agenda()" class="mb-2 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-gray-200 p-4 dark:border-gray-700"><button class="min-h-11 text-left text-sm font-semibold hover:text-blue-600" (click)="open(task)">{{task.title}}</button><span class="text-xs text-gray-600 dark:text-gray-300">{{task.dueDate | date:'dd/MM/yyyy'}} · {{task.status==='done' ? 'Terminé' : task.status==='in-progress' ? 'En cours' : 'À faire'}}</span></div><p *ngIf="!agenda().length" class="text-sm text-gray-600 dark:text-gray-300">Aucune échéance ce mois-ci. Ajoutez une date dans les détails d’une tâche.</p></section>
 <p class="mt-8 text-sm text-gray-600 dark:text-gray-300">{{undated()}} tâches sans échéance. <a routerLink="/board" class="text-blue-700 underline dark:text-blue-300">Retour au tableau</a></p>
 <app-task-modal *ngIf="selected" [task]="selected" [mode]="mode" [error]="error()" (close)="selected=null" (save)="save($event)" (subTaskToggle)="toggleSubTask($event)" />
</app-page-shell>`})
export class CalendarComponent {
 private readonly storage=inject(STORAGE_PROVIDER);
 readonly tasks=inject(TaskService); readonly cursor=signal(new Date()); readonly error=signal(''); selected:Task|null=null; mode:'view'|'edit'='edit';
 readonly weekdays=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'];
 readonly days=computed(()=>calendarDays(this.cursor().getFullYear(),this.cursor().getMonth()));
 readonly monthLabel=computed(()=>this.cursor().toLocaleDateString('fr-FR',{month:'long',year:'numeric'}));
 readonly agenda=computed(()=>this.tasks.activeTasks().filter(t=>t.dueDate&&new Date(t.dueDate).getMonth()===this.cursor().getMonth()&&new Date(t.dueDate).getFullYear()===this.cursor().getFullYear()).sort((a,b)=>new Date(a.dueDate!).getTime()-new Date(b.dueDate!).getTime()));
 readonly undated=computed(()=>this.tasks.activeTasks().filter(t=>!t.dueDate).length);
 constructor(){if(this.storage.contextVersion)effect(()=>{this.storage.contextVersion!();untracked(()=>{this.selected=null;this.error.set('');});});}
 tasksFor(day:Date){return this.agenda().filter(t=>localDayKey(new Date(t.dueDate!))===localDayKey(day));}
 isToday(day:Date){return localDayKey(day)===localDayKey(new Date());}
 move(delta:number){this.cursor.update(d=>new Date(d.getFullYear(),d.getMonth()+delta,1));} today(){this.cursor.set(new Date());}
 open(task:Task){this.selected=task;this.error.set('');}
 save(task:Task){try{this.tasks.updateTask(task);this.selected=null;}catch(e){this.error.set(e instanceof Error?e.message:'Enregistrement impossible.');}}
 toggleSubTask(id:string){if(!this.selected)return;try{this.tasks.toggleSubTask(this.selected.id,id);this.selected=this.tasks.tasks().find(t=>t.id===this.selected!.id)??null;}catch(e){this.error.set(e instanceof Error?e.message:'Modification impossible.');}}
}

@Component({standalone:true,imports:[...imports],template:`
<app-page-shell title="Profil et paramètres" description="Votre compte et vos préférences d’affichage."><section class="grid gap-4 sm:grid-cols-2"><article class="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><h2 class="text-lg font-semibold">Mon profil</h2><p class="mt-4 text-sm text-gray-600 dark:text-gray-300">La gestion de votre session et de votre compte reste accessible depuis l’espace compte.</p><a routerLink="/login" class="primary mt-4 min-h-11">Gérer mon compte</a><p class="mt-4 text-xs text-gray-600 dark:text-gray-300">La modification du nom et de l’adresse email n’est pas encore disponible sur cette page.</p></article><article class="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><h2 class="text-lg font-semibold">Apparence</h2><p class="my-4 text-sm text-gray-600 dark:text-gray-300">Préférence conservée sur cet appareil. Vos couleurs et votre typographie Ma’at restent identiques.</p><button class="secondary min-h-11" [attr.aria-pressed]="theme.darkMode()" (click)="theme.toggleDarkMode()">{{theme.darkMode() ? 'Passer au thème clair' : 'Passer au thème sombre'}}</button></article></section><section class="mt-4 rounded-xl border border-gray-200 p-4 dark:border-gray-700"><h2 class="font-semibold">Sauvegarde et récupération</h2><p class="mt-2 text-sm leading-6 text-gray-600 dark:text-gray-300">Ouvrez le menu de votre compte, puis « Sauvegarde et récupération » pour exporter vos copies ou résoudre un problème de synchronisation. Ne supprimez pas vos données navigateur avant d’avoir téléchargé une sauvegarde.</p><a routerLink="/help" class="secondary mt-4 min-h-11">Comprendre les sauvegardes</a></section></app-page-shell>`})
export class SettingsComponent {readonly theme=inject(ThemeService);}

@Component({standalone:true,imports,template:`
<app-page-shell title="Équipe et invitations" description="Un futur espace pour travailler ensemble, sans exposer vos tâches personnelles."><section class="rounded-xl border border-blue-200 bg-blue-50 p-8 dark:border-blue-900 dark:bg-blue-950"><p class="text-xs font-semibold uppercase text-blue-700 dark:text-blue-300">Collaboration non activée</p><h2 class="mt-4 text-xl font-semibold">Votre espace reste personnel.</h2><p class="mt-4 max-w-2xl text-sm leading-6 text-gray-600 dark:text-gray-300">Aucune invitation n’est envoyée depuis cette page. Aucun membre n’est ajouté et aucun accès à vos tâches n’est partagé. Les comptes administrateurs de l’application ne sont pas des membres de vos projets.</p><a routerLink="/projects" class="primary mt-4 min-h-11">Organiser mes projets</a></section><section class="mt-8"><h2 class="mb-4 text-lg font-semibold">Avant d’activer les invitations</h2><ol class="list-inside list-decimal space-y-4 text-sm text-gray-600 dark:text-gray-300"><li>Créer les espaces partagés et les règles d’accès en base.</li><li>Définir les rôles propriétaire, éditeur et lecteur.</li><li>Ajouter des invitations expirables, leur acceptation et leur révocation.</li><li>Tester que chaque équipe accède uniquement à ses données.</li></ol></section></app-page-shell>`})
export class TeamComponent {}

@Component({standalone:true,imports,template:`
<app-page-shell title="Aide et démarrage" description="Les premiers pas pour garder un espace simple et fiable."><section class="grid gap-4 sm:grid-cols-3"><article *ngFor="let step of steps; let i=index" class="rounded-xl border border-gray-200 p-4 dark:border-gray-700"><p class="text-xs text-blue-700 dark:text-blue-300">Étape {{i+1}}</p><h2 class="mt-2 font-semibold">{{step.title}}</h2><p class="mt-2 text-sm leading-6 text-gray-600 dark:text-gray-300">{{step.text}}</p><a [routerLink]="step.link" class="secondary mt-4 min-h-11">{{step.action}}</a></article></section><section class="mt-8"><h2 class="mb-4 text-lg font-semibold">Questions fréquentes</h2><details *ngFor="let item of faq" class="mb-2 rounded-xl border border-gray-200 p-4 dark:border-gray-700"><summary class="min-h-11 cursor-pointer py-2 font-semibold">{{item.q}}</summary><p class="mt-2 text-sm leading-6 text-gray-600 dark:text-gray-300">{{item.a}}</p></details></section><p class="mt-8 text-sm text-gray-600 dark:text-gray-300">Raccourcis dans le tableau : N pour créer une tâche, / pour rechercher. Ils sont désactivés pendant la saisie d’un champ.</p></app-page-shell>`})
export class HelpComponent {
 readonly steps=[{title:'Créez une tâche',text:'Ajoutez un titre, une priorité et, si utile, une échéance.',link:'/board',action:'Ouvrir le tableau'},{title:'Structurez un projet',text:'Créez un projet puis associez vos tâches depuis leurs détails.',link:'/projects',action:'Mes projets'},{title:'Vérifiez la sauvegarde',text:'Connectez-vous et attendez la confirmation de synchronisation.',link:'/login',action:'Mon compte'}];
 readonly faq=[{q:'Où sont mes tâches sans compte ?',a:'Sur cet appareil. Elles ne sont pas automatiquement disponibles sur un autre navigateur. Exportez une sauvegarde avant de vider les données du navigateur.'},{q:'Que signifie « Sauvegardé » ?',a:'La synchronisation avec le compte est confirmée. Si un message de conflit ou d’erreur apparaît, utilisez les outils de récupération du menu compte avant de quitter la session.'},{q:'Pourquoi une tâche n’apparaît-elle pas ?',a:'Vérifiez les filtres de statut, de projet et les filtres avancés. Effacez les filtres et consultez les archives.'},{q:'Comment utiliser le calendrier ?',a:'Renseignez une échéance dans les détails de la tâche. Le calendrier affiche les échéances des tâches actives ; les tâches archivées n’y figurent pas.'},{q:'Puis-je inviter une équipe ?',a:'Pas encore. Les projets sont personnels et la page Équipe décrit ce qui reste à activer.'}];
}

@Component({standalone:true,imports,template:`
<app-page-shell title="Confidentialité" description="Informations sur les données utilisées par Ma’at."><p role="note" class="mb-8 rounded-lg bg-blue-50 p-4 text-sm text-blue-800 dark:bg-blue-950 dark:text-blue-200">Document provisoire : l’identité de l’éditeur, le contact confidentialité, les durées de conservation et la procédure d’exercice des droits doivent être renseignés et validés avant une ouverture publique.</p><section *ngFor="let section of sections" class="mb-8 max-w-3xl"><h2 class="text-lg font-semibold">{{section.title}}</h2><p class="mt-2 text-sm leading-7 text-gray-600 dark:text-gray-300">{{section.text}}</p></section></app-page-shell>`})
export class PrivacyComponent {readonly sections=[{title:'Données traitées',text:'L’application utilise vos informations de compte et le contenu que vous saisissez : tâches, sous-tâches, projets, objectifs et échéances. Ne saisissez pas de données sensibles inutiles à votre organisation.'},{title:'Stockage et services techniques',text:'Le mode local conserve les données dans votre navigateur. Le mode connecté utilise Supabase pour le compte et la sauvegarde cloud. L’application est hébergée sur Vercel. La préférence de thème est conservée sur votre appareil.'},{title:'Accès et partage',text:'Les projets actuels sont personnels. La collaboration n’est pas activée. L’administration sert à la gestion de l’application et ne doit pas donner accès aux tâches privées par défaut.'},{title:'Copies et suppression',text:'Les fonctions d’export permettent de conserver une copie de vos tâches. Une procédure de suppression complète du compte, des données cloud et des sauvegardes doit encore être définie ; vider le navigateur ne supprime pas les données cloud.'},{title:'Contact et droits',text:'Le responsable du traitement et son adresse de contact restent à préciser. Cette page ne constitue pas une déclaration de conformité juridique.'}];}

@Component({standalone:true,imports,template:`
<app-page-shell title="Conditions d’utilisation" description="Cadre provisoire d’utilisation de Ma’at."><p class="mb-8 rounded-lg bg-blue-50 p-4 text-sm text-blue-800 dark:bg-blue-950 dark:text-blue-200">Projet de conditions à compléter et faire valider avant une ouverture publique. L’éditeur et le contact de support ne sont pas encore renseignés.</p><section *ngFor="let section of sections" class="mb-8 max-w-3xl"><h2 class="text-lg font-semibold">{{section.title}}</h2><p class="mt-2 text-sm leading-7 text-gray-600 dark:text-gray-300">{{section.text}}</p></section><a routerLink="/privacy" class="secondary min-h-11">Lire la page confidentialité</a></app-page-shell>`})
export class TermsComponent {readonly sections=[{title:'Objet du service',text:'Ma’at est un gestionnaire de tâches personnel en cours de développement. Certaines fonctions, notamment la collaboration et les invitations, ne sont pas disponibles.'},{title:'Votre compte',text:'Protégez vos identifiants et utilisez les fonctions de déconnexion. Vous restez responsable du contenu que vous saisissez et ne devez pas utiliser l’application pour des activités illicites.'},{title:'Disponibilité et sauvegardes',text:'L’application ne propose pas de garantie de disponibilité. Vérifiez les confirmations de synchronisation et conservez régulièrement des exports, particulièrement avant de supprimer des données locales.'},{title:'Fonctions en évolution',text:'Les fonctionnalités peuvent évoluer. Les règles de suspension, de suppression du compte, les responsabilités de l’éditeur et le droit applicable restent à définir dans la version définitive des conditions.'}];}

@Component({standalone:true,imports,template:`
<app-page-shell title="Cette page n’existe pas" description="Le lien est peut-être ancien ou l’adresse contient une erreur."><section class="rounded-2xl border border-gray-200 p-8 text-center dark:border-gray-700"><p class="text-6xl font-semibold text-blue-600 dark:text-blue-300">404</p><h2 class="mt-4 text-xl font-semibold">Retrouvons votre chemin.</h2><div class="mt-8 flex flex-wrap justify-center gap-4"><a routerLink="/board" class="primary min-h-11">Mon tableau</a><a routerLink="/presentation" class="secondary min-h-11">Découvrir Ma’at</a><a routerLink="/help" class="secondary min-h-11">Aide</a></div></section></app-page-shell>`})
export class NotFoundComponent {}
