begin;
do $$
declare tid uuid;owner uuid;worker uuid;pid uuid;task uuid;sub uuid;recorded uuid;n integer;
begin
 select t.id,t.owner_id,m.user_id into tid,owner,worker from public.taskboard_teams t join public.taskboard_team_members m on m.team_id=t.id and m.user_id<>t.owner_id limit 1;
 if tid is null then raise exception 'Test requires an existing team with two members';end if;
 perform set_config('request.jwt.claim.sub',owner::text,true);
 insert into public.taskboard_shared_projects(team_id,title) values(tid,'__notification_test_rollback__') returning id into pid;
 insert into public.taskboard_shared_tasks(project_id,team_id,title,assignee_id,assigned_by) values(pid,tid,'Completion test',worker,worker) returning id,assigned_by into task,recorded;
 if recorded<>owner then raise exception 'assignment author spoofed';end if;
 update public.taskboard_shared_tasks set assigned_by=worker where id=task;
 select assigned_by into recorded from public.taskboard_shared_tasks where id=task;
 if recorded<>owner then raise exception 'immutable author spoofed';end if;
 insert into public.taskboard_shared_subtasks(task_id,team_id,title,assignee_id) values(task,tid,'Subtask test',worker) returning id into sub;
 perform set_config('request.jwt.claim.sub',worker::text,true);
 perform public.progress_taskboard_work(sub,true,'done');
 select count(*) into n from public.taskboard_notifications where project_id=pid and user_id=owner and title='Sous-tâche terminée : Subtask test';
 if n<>1 then raise exception 'subtask completion failed';end if;
 perform public.progress_taskboard_work(sub,true,'done');
 select count(*) into n from public.taskboard_notifications where project_id=pid and title='Sous-tâche terminée : Subtask test';
 if n<>1 then raise exception 'duplicate subtask notification';end if;
 perform public.progress_taskboard_work(task,false,'done');
 select count(*) into n from public.taskboard_notifications where project_id=pid and user_id=owner and title='Tâche terminée : Completion test';
 if n<>1 then raise exception 'task completion failed';end if;
 perform public.progress_taskboard_work(task,false,'done');
 update public.taskboard_shared_tasks set description='same status' where id=task;
 select count(*) into n from public.taskboard_notifications where project_id=pid and title='Tâche terminée : Completion test';
 if n<>1 then raise exception 'duplicate task notification';end if;
 perform set_config('request.jwt.claim.sub',owner::text,true);
 perform public.progress_taskboard_work(task,false,'in-progress');
 perform public.progress_taskboard_work(task,false,'done');
 select count(*) into n from public.taskboard_notifications where project_id=pid and title='Tâche terminée : Completion test';
 if n<>1 then raise exception 'self notification';end if;
 perform set_config('request.jwt.claim.sub','',true);
 insert into public.taskboard_shared_tasks(project_id,team_id,title,assignee_id) values(pid,tid,'Legacy completion test',worker) returning id into task;
 perform set_config('request.jwt.claim.sub',worker::text,true);
 perform public.progress_taskboard_work(task,false,'done');
 select count(*) into n from public.taskboard_notifications where project_id=pid and user_id=owner and title='Tâche terminée : Legacy completion test';
 if n<>1 then raise exception 'legacy owner fallback';end if;
end;$$;
rollback;
select 'completion, deduplication, self suppression, author protection and legacy fallback passed; all test data rolled back' as result;
