import { Injectable, inject, signal } from '@angular/core';
import { AuthService } from './auth.service';
export type TeamRole='owner'|'admin'|'member'|'viewer';
export interface Team{id:string;owner_id:string;name:string;created_at:string;}
export interface TeamInvitation{id:string;team_id:string;email:string;role:Exclude<TeamRole,'owner'>;expires_at:string;created_at:string;}
@Injectable({providedIn:'root'}) export class TeamService{
 private readonly auth=inject(AuthService); readonly teams=signal<Team[]>([]); readonly invitations=signal<TeamInvitation[]>([]);
 async load(){const {data,error}=await this.auth.client.from('taskboard_teams').select('*').order('created_at',{ascending:false});if(error)throw new Error('Chargement des équipes impossible.');this.teams.set((data??[]) as Team[]);const ids=(data??[]).map((x:{id:string})=>x.id);if(ids.length){const r=await this.auth.client.from('taskboard_team_invitations').select('id,team_id,email,role,expires_at,created_at').in('team_id',ids).is('accepted_at',null).order('created_at',{ascending:false});if(!r.error)this.invitations.set((r.data??[]) as TeamInvitation[]);}}
 async create(name:string){const user=this.auth.user(),clean=name.trim();if(!user)throw new Error('Connectez-vous pour créer une équipe.');if(clean.length<2)throw new Error('Donnez un nom à votre équipe.');const {data,error}=await this.auth.client.from('taskboard_teams').insert({owner_id:user.id,name:clean}).select().single();if(error)throw new Error('Création impossible : '+error.message);const team=data as Team;const member=await this.auth.client.from('taskboard_team_members').insert({team_id:team.id,user_id:user.id,role:'owner'});if(member.error)throw new Error('Équipe créée mais propriétaire non enregistré.');this.teams.update(items=>[team,...items]);}
 async invite(teamId:string,email:string,role:Exclude<TeamRole,'owner'>){const user=this.auth.user(),clean=email.trim().toLowerCase();if(!user)throw new Error('Connectez-vous pour inviter un membre.');if(!/^\S+@\S+\.\S+$/.test(clean))throw new Error('Adresse email invalide.');const {data,error}=await this.auth.client.from('taskboard_team_invitations').insert({team_id:teamId,email:clean,role,invited_by:user.id,token_hash:crypto.randomUUID()+crypto.randomUUID()}).select('id,team_id,email,role,expires_at,created_at').single();if(error)throw new Error('Invitation impossible : '+error.message);this.invitations.update(items=>[data as TeamInvitation,...items]);}
}
